//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplicationObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_DeptTable
    {
        public M_DeptTable()
        {
            this.M_StudentTable = new HashSet<M_StudentTable>();
        }
    
        public int DeptId { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
    
        public virtual ICollection<M_StudentTable> M_StudentTable { get; set; }
    }
}
