//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplicationObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_StudentTable
    {
        public int StudId { get; set; }
        public int DeptId { get; set; }
        public string StudCode { get; set; }
        public string Name { get; set; }
    
        public virtual M_DeptTable M_DeptTable { get; set; }
    }
}
